[package]
name = "cyd"
description = "Convert your data"
version = "0.1.0"
authors = ["David O'Rourke <david.orourke@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
toml = "0.5"
